  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./docker/blocks/self-instrumentation/prometheus.yaml:/etc/prometheus/prometheus.yml
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
  promtail:
    image: grafana/promtail:latest
    command: -config.file=/etc/promtail/promtail.yaml
    volumes:
      - ./docker/blocks/self-instrumentation/promtail.yaml:/etc/promtail/promtail.yaml
      - ../data/log:/var/log/grafana
  tempo:
    image: grafana/tempo:latest
    command: -config.file=/etc/tempo.yaml
    volumes:
      - ./docker/blocks/self-instrumentation/tempo.yaml:/etc/tempo.yaml
    ports:
      - "14268:14268"
      - "3200:3200"
  agent:
    image: grafana/agent:latest
    volumes:
      - ./docker/blocks/self-instrumentation/tempo.yaml:/etc/tempo.yaml
  agent:
    image: grafana/agent:latest
    volumes:
      - ./config:/etc/agent-config
    entrypoint:
      - /bin/agent
      - -server.http.address=0.0.0.0:12345
      - -config.file=/etc/agent/agent.yaml
      - -metrics.wal-directory=/tmp/agent/wal
      - -enable-features=integrations-next
      - -config.expand-env
      - -config.enable-read-api
    environment:
      HOSTNAME: agent
      REMOTE_WRITE_HOST: cortex:9009
      LOKI_HOST: loki:3100
      TEMPO_HOST: tempo:4317
      AVALANCHE_HOST: avalanche:9001
      MYSQL_HOST: mysql:3306
      POSTGRES_HOST: postgres:5432
      REDIS_HOST: redis:6379
      DNSMASQ_HOST: dnsmasq:53
      MEMCACHED_HOST: memcached:11211
      CONSUL_HOST: consul:8500
      ELASTICSEARCH_HOST: elasticsearch:9200
      KAFKA_HOST: kafka:9093
      MONGODB_HOST: mongodb:27017
    ports:
      - "12345:12345"
