  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./docker/blocks/self-instrumentation/prometheus.yaml:/etc/prometheus/prometheus.yaml
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
  promtail:
    image: grafana/promtail:latest
    command: -config.file=/etc/promtail/promtail.yaml
    volumes:
      - ./docker/blocks/self-instrumentation/promtail.yaml:/etc/promtail/promtail.yaml
      - ../data/log:/var/log/grafana
  tempo:
    image: grafana/tempo:latest
    command: -config.file=/etc/tempo.yaml
    volumes:
      - ./docker/blocks/self-instrumentation/tempo.yaml:/etc/tempo.yaml
    ports:
      - "14268:14268"
      - "3200:3200"
